### ISSUE TITLE
Nuxt 2 & Vue 2 support

### ISSUE THREAD

**Issue by Elliot67** [wobsoriano/vue-wrap-balancer#2]
Since the library is using `vue-demi`, I guess it should be compatible with Nuxt 2 & Vue 2 but I can't get it to work.
Is it compatible ? If yes how do you import it ?

Thx for making the port to Vue ! 💚

**Comment by wobsoriano** [comment]
Hey, I have not tried it but I expect it to work as long as you have composition-api plugin or vue 2.7 installed?

**Comment by Elliot67** [comment]
Tried with composition-api and with vue 2.7. Made a reproduction [on stackblitz](https://stackblitz.com/edit/github-pmz4cn?file=pages/index.vue) with the latest nuxt 2 version which includes Vue 2.7.
I'm not extremely familiar with Nuxt, the problem might come from me.

**Comment by wobsoriano** [comment]
Okay, I will have to do some updates since Vue 2 doesn't have `withDirectives` function.

**Comment by wobsoriano** [comment]
As stated [here](https://github.com/vueuse/vue-demi/issues/60), functions like `withDirectives` isn't available in Vue 2 so I published a different package in this [branch](https://github.com/wobsoriano/vue-wrap-balancer/tree/vue2) instead:

```bash
npm install vue2-wrap-balancer
```

Here's the forked repro btw - [stackblitz](https://stackblitz.com/edit/github-pmz4cn-qat7bu?file=pages%2Findex.vue)

**Comment by Elliot67** [comment]
Works perfectly, thx!
