### ISSUE TITLE
`class` is not inherited

### ISSUE THREAD

**Issue by lukaszflorczak** [wobsoriano/vue-wrap-balancer#4]
It's similar to that: https://github.com/wobsoriano/vue-wrap-balancer/pull/3 and it looks like the `class` value is not inherited too. 

Shouldn't be all `$attrs` bound by default?

**Comment by wobsoriano** [comment]
Are you in Vue 2 or 3?

**Comment by wobsoriano** [comment]
> it looks like the class value is not inherited too.

Are you on Vue 2 or 3?

<img width="1133" alt="Screenshot 2023-01-30 at 8 22 37 AM" src="https://user-images.githubusercontent.com/13049130/215533925-4702fc4a-9cc3-483f-8f26-5e88b0275219.png">

> Shouldn't be all $attrs bound by default?

It doesn't have a root element

**Comment by lukaszflorczak** [comment]
Nuxt 2 + Vue 2. The reproduction is here: https://stackblitz.com/edit/github-pmz4cn-h9kozt?file=pages/index.vue. There are no `id`, `class`, or `data` attributes.

> It doesn't have a root element

In the template? I know you create it programmatically. Vue 3 probably includes all attributes automatically by default, but Vue 2 doesn't. 

Maybe this is not a big problem in a new project (although I would also prefer to avoid unnecessary element nesting, and the problem especially occurs if you need to use `v-html`). But I'm trying to implement a balancer in a working project, where I need to keep the existing structure and this is already a big problem.
